services:
  aiohttp-app:
    build:
      context: .
      dockerfile: ../../base/python/python3.11-slim/Dockerfile
    container_name: aiohttp
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static:ro
    restart: unless-stopped
