services:
  aiohttp-app:
    build:
      context: .
      dockerfile: ../../base/python/aiohttp/3.9.1/Dockerfile
    container_name: aiohttp
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static:ro
    restart: unless-stopped
